### ISSUE TITLE
Zero Shot works poorly

### ISSUE THREAD

**Issue by weny911** [BMVC-FADE/BMVC-FADE#3]
![0shot](https://github.com/user-attachments/assets/137e4ad8-9db1-49f4-a736-1aeb8cde2bba)

My configuration：
torch                     2.5.1
torchvision               0.20.1
python               3.10
open_clip_torch           2.29.0
cuda           11.8

use this command line :  `python scripts/run_fade.py --dataset-name mvtec --dataset-source data/mvtec --experiment-name mvtec/zeroshot/cm_both_sm_both_clip_gem_gem/img_size_0 --classification-mode both --segmentation-mode both --shots 0 --language-classification-feature clip --language-segmentation-feature gem --vision-feature gem --vision-segmentation-multiplier 80.0 --vision-segmentation-weight 0.5 --use-query-img-in-vision-memory-bank`

the models can be downloaded with the links from [https://github.com/mlfoundations/open_clip/releases/download/v0.2-weights/vit_b_16_plus_240-laion400m_e31-8fb26589.pt](url)

Dear author, thank you for your work, the above is my configuration, and the rest are left by default, why is the effect really bad?  Is it me configuring it wrong?

**Comment by quanw7755** [comment]
Hello, Apart from the zero-shot scenario, have you managed to reproduce the results for other few-shot settings as reported in the paper? If you have successfully reproduced them, could you please provide an explanation?

**Comment by lisaivanova** [comment]
Hi @liwenyang-911!

Could you please try downgrading to 
torch=2.2.0
open_clip_torch=2.24.0
torchvision=0.17.0

The weights and the command look correct. Let me run the script and I will get back to you shortly.

**Comment by lisaivanova** [comment]
Here are my results for the bottle with your command:

```
Object: bottle
Full image AUROC: 0.98
Full pixel AUROC: 0.89
Anomaly pixel AUROC: 0.87
```

So please try to run it with the older versions from my previous message.

**Comment by weny911** [comment]
> Here are my results for the bottle with your command:
> 
> ```
> Object: bottle
> Full image AUROC: 0.98
> Full pixel AUROC: 0.89
> Anomaly pixel AUROC: 0.87
> ```
> 
> So please try to run it with the older versions from my previous message.

I tried again after adjusting the version of the package in line with you, and I successfully calculated a good result, thanks again to the author.

**Comment by weny911** [comment]
> Here are my results for the bottle with your command:
> 
> ```
> Object: bottle
> Full image AUROC: 0.98
> Full pixel AUROC: 0.89
> Anomaly pixel AUROC: 0.87
> ```
> 
> So please try to run it with the older versions from my previous message.

Another thing I want to ask the author is, this is the result of Zero Shot, it doesn't look very good, why did it get such a high score？
![image](https://github.com/user-attachments/assets/41569185-a010-42a3-82e6-d12347a559f5)

**Comment by weny911** [comment]
> Hello, Apart from the zero-shot scenario, have you managed to reproduce the results for other few-shot settings as reported in the paper? If you have successfully reproduced them, could you please provide an explanation?

If you want to try a few shots, you can use the following command:
`python scripts/run_fade.py --dataset-name mvtec --dataset-source data/mvtec --experiment-name mvtec/fewshot/cm_both_sm_both_clip_gem_gem/img_size_0 --classification-mode both --segmentation-mode both --shots 5 --language-classification-feature clip --language-segmentation-feature gem --vision-feature gem --vision-segmentation-multiplier 3.5 --vision-segmentation-weight 0.85`

**Comment by quanw7755** [comment]
> 嗨 ！
> 
> 您能否尝试降级到 torch=2.2.0 open_clip_torch=2.24.0 torchvision=0.17.0
> 
> 权重和命令看起来正确。让我运行脚本，我很快就会回复您。

Thank you, Author. It has run successfully.

**Comment by quanw7755** [comment]
![image](https://github.com/user-attachments/assets/e3155c25-5e77-4766-9147-d9f697736eec)
Hello, why did the zero-shot performance not improve even after modifying the version you provided?
